apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    run: kuard
  name: kuard
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: kuard
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kuard
      annotations:
        kubernetes.io/change-cause: "Testing rollout" # will be sent to k8s api
    spec:
      containers:
      - image: jodicl/kuard-amd64
        imagePullPolicy: Always
        name: kuard
      terminationGracePeriodSeconds: 30
