---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  volumes:
    - name: "kuard-data"
      # mounts path below on worker node into container
      hostPath:
        path: "/var/lib/kuard"
  containers:
    - image: jodicl/kuard-amd64
      name: kuard
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP

