---
apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers: 
    - image: jodicl/kuard-amd64
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
